import Link from "next/link";
import type { InstructionPanelProps } from "@/lib/base/types/componentTypes"

/**
 * InstructionPanel Component
 *
 * Displays a tools description, usage steps, optional default info,
 * and a privacy notice. Markdown formatting is supported in text fields.
 */
export default function InstructionPanel(props: InstructionPanelProps) {
    return (
        <div className="app-panel">
            <div className="card-light text-primary">
                <div className="card-body">
                    {/* Section: What the tool does */}
                    <h3>🛠️ What This Tool Does</h3>
                    <div>{props.description}</div>

                    {/* Section: How to use it */}
                    <div>
                        <h4 className="pt-3">📋 How to Use It</h4>
                        <div>
                            {props.steps.map((step, i) => {
                                return (
                                    <div key={`step-${i}`} className="icon-list">
                                        <span className="icon-list__icon">{step.icon}</span>
                                        {step.text}
                                    </div>
                                );
                            })}
                            <p className="ps-2 pt-1 text-sm text-base-content/80">
                                For more detailed instructions, see the <Link className="link-hash" href={`/docs?tab=${props.app}`}>{props.app} documentation</Link>.
                            </p>
                        </div>
                    </div>

                    {/* Section: Defaults description */}
                    {props.defaultsDescription && (
                        <div>
                            <h4 className="pt-6">ℹ️ About the Defaults</h4>
                            <div className="pt-1">{props.defaultsDescription}</div>
                        </div>
                    )}

                    {/* Section: Privacy notice */}
                    <div className="flex items-start gap-2 pt-3 text-xs text-base-content/70">
                        <p className="whitespace-nowrap">
                            🔒 <strong>Privacy Notice:</strong>
                        </p>
                        <p>
                            Your inputs are never stored. Only the output files generated by this tool
                            are retained temporarily to facilitate downloads.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
