import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import {headers} from 'next/headers';
import {isRTL} from 'react-aria-components';
import Header from "@/components/layout/header"
import Footer from "@/components/layout/footer";
import {ClientProviders} from './provider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    // Get the user's preferred language from the Accept-Language header.
    // You could also get this from a database, URL param, etc.
    const acceptLanguage = (await headers()).get('accept-language');
    const lang = acceptLanguage?.split(/[,;]/)[0] || 'en-US';

  return (
    <html lang={lang} dir={isRTL(lang) ? 'rtl' : 'ltr'} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ClientProviders lang={lang}>
        <div className="flex flex-col min-h-screen bg-base-100">
          {/* Site header */}
          <Header />

          {/* Main content */}
          <main className="grow px-4">
              {children}
          </main>

          {/* Site footer */}
          <Footer />
      </div>
      </ClientProviders>
      </body>
    </html>
  );
}
